# Generated by Django 5.0.1 on 2024-01-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='business_email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='business_website',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='whatsup_link',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
